# Generated by Django 2.0.5 on 2018-05-30 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dest',
            old_name='dest_name',
            new_name='dest_title',
        ),
    ]
